:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\GeneratedAPI
dotnet build src\GeneratedAPI
echo Now, run the following to start the project: dotnet run -p src\GeneratedAPI\GeneratedAPI.csproj --launch-profile web.
echo.
